name: 'Cy Giacomin, Composer/Arranger'
favicon: null
layout_spectrum: 0.8449342180974782
typography_spectrum: 0.0961681455373764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.013279419159516692
  lightness: 0.37735149008221924
  saturation: 0.6215092793572694
  rhythmicContrast: 0.8522605416364968
purpose: []
